# Generated by Django 4.2.5 on 2023-09-09 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=8)),
                ('short_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SharePriceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('source', models.CharField(max_length=64)),
                ('price_map', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('weights_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Briefcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.JSONField()),
                ('favorites', models.TextField()),
                ('ignored', models.TextField()),
                ('capital', models.PositiveBigIntegerField(default=1000000)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shares.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefcases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
