# Generated by Django 4.2.5 on 2023-09-09 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefcase',
            name='favorites',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='briefcase',
            name='ignored',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='briefcase',
            name='shares',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='sharepriceblock',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='weights_json',
            field=models.JSONField(default=dict),
        ),
    ]
