# Generated by Django 4.2.5 on 2023-09-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0003_fill_init_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefcase',
            name='favorites',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='briefcase',
            name='ignored',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='briefcase',
            name='shares',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='share',
            name='ticker',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='sharepriceblock',
            name='dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
