# Generated by Django 4.2.5 on 2023-09-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0006_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='price_target',
            field=models.DecimalField(decimal_places=4, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='row',
            name='price_to_buy',
            field=models.DecimalField(decimal_places=4, default='0.00', max_digits=10),
        ),
    ]
