# Generated by Django 4.2.5 on 2023-09-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0007_alter_row_price_target_alter_row_price_to_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='briefcase',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='briefcase',
            name='ignored',
        ),
        migrations.RemoveField(
            model_name='briefcase',
            name='shares',
        ),
    ]
