# Generated by Django 4.2.5 on 2023-09-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0008_remove_briefcase_favorites_remove_briefcase_ignored_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='figi',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='instrument_uid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='share',
            name='lotsize',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
